## Version 2025/05/23
# make sure that your cleanuparr container is named cleanuparr
# make sure that your dns has a cname set for cleanuparr

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name cleanuparr.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    location / {
        include /config/nginx/proxy.conf;
        include /config/nginx/resolver.conf;
        set $upstream_app cleanuparr;
        set $upstream_port 11011;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
    }
}
