// @ts-check
// Project-aware flat config generated by the @nuxt/eslint module. It knows
// Nuxt's auto-imports (defineNuxtConfig, defineAppConfig, $fetch, etc.) and
// applies the correct TypeScript/Vue parsers per file. Regenerated into
// .nuxt/eslint.config.mjs by `nuxt prepare` (runs on postinstall).
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt()
