#!/usr/bin/env python3
"""Generate the cron-fleet tables in docs/music-pipeline-integration.md.

Why this is generated and not written by hand
---------------------------------------------
The hand-maintained tables have pointed at the wrong script **twice**:

* Section 5 credited `slskd_complete_sweep.py` with clearing `Completed,*`
  transfer records and `slskd_cleanup.py` with disk cruft. They are the other
  way round. Anyone deciding which script to retire from that table would have
  retired the load-bearing one -- and given that slskd's file retention is
  inert, that is exactly the one that must stay.
* Section 9 listed one daily `05:05` library scan. There are three weekly
  per-library scans, and it listed four holders of the cleanup flock when there
  are five.

Both times the **docstrings were right** and the table was wrong. So the table
is now derived from the docstrings and from `cron/crontab`, and `make check`
fails when the committed doc no longer matches what this produces. A table
describing 32 job lines will drift again; the only question is whether anything
notices.

The first line of each script's module docstring is its summary -- that is a
convention this repo already follows, and it is what appears in the table.

Usage
-----
  python scripts/gen_pipeline_tables.py            # print the tables
  python scripts/gen_pipeline_tables.py --check    # exit 1 if the doc differs

Exit codes
----------
  0  the doc matches (or --check was not given)
  1  the doc's generated block is stale -- re-run with --write
  2  the crontab or a referenced script is missing
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CRONTAB = REPO / "cron" / "crontab"
DOC = REPO / "docs" / "music-pipeline-integration.md"

BEGIN = "<!-- BEGIN GENERATED: cron-fleet -->"
END = "<!-- END GENERATED: cron-fleet -->"

JOB = re.compile(r"--name (?P<name>[a-z0-9-]+)")
LOCK = re.compile(r"--lock (?P<lock>\S+)")
LOCK_WAIT = re.compile(r"--lock-wait (?P<wait>\d+)")
OK_CODES = re.compile(r"--ok-codes (?P<codes>[\d,]+)")
SCRIPT = re.compile(r"python scripts/(?P<script>[a-z0-9_]+\.py)")


def schedule_of(line: str) -> str:
  """The five cron fields, as written."""
  return " ".join(line.split()[:5])


def summary_of(script: str) -> str:
  """First line of the script's module docstring -- the repo's own convention."""
  path = REPO / "scripts" / script
  if not path.exists():
    return "(script not found)"
  try:
    doc = ast.get_docstring(ast.parse(path.read_text()))
  except SyntaxError:
    return "(unparseable)"
  if not doc:
    return "(no docstring)"
  return doc.splitlines()[0].strip().rstrip(".")


def jobs(crontab_text: str) -> list[dict]:
  """Every scheduled cron_job.py entry, in crontab order."""
  found = []
  for line in crontab_text.splitlines():
    if line.startswith("#") or "cron_job.py" not in line:
      continue
    name = JOB.search(line)
    if not name:
      continue
    # The wrapped script is the one after `--`, not cron_job.py itself.
    after = line.split(" -- ", 1)[-1]
    script = SCRIPT.search(after)
    lock = LOCK.search(line)
    wait = LOCK_WAIT.search(line)
    codes = OK_CODES.search(line)
    found.append(
      {
        "schedule": schedule_of(line),
        "name": name.group("name"),
        "script": script.group("script") if script else "(shell command)",
        "lock": lock.group("lock") if lock else "",
        "wait": wait.group("wait") if wait else "",
        "ok_codes": codes.group("codes") if codes else "0,1 (default)",
      }
    )
  return found


def render(found: list[dict]) -> str:
  """The full generated block, including the lock-contention summary."""
  out = [BEGIN, ""]
  out.append(f"_Generated by `scripts/gen_pipeline_tables.py` from `cron/crontab`. "
             f"{len(found)} scheduled jobs._")
  out.append("")
  out.append("| Schedule | Job | Script | What it does | `--ok-codes` |")
  out.append("| --- | --- | --- | --- | --- |")
  out.extend(
    f"| `{job['schedule']}` | `{job['name']}` | `{job['script']}` | "
    f"{summary_of(job['script']) if job['script'].endswith('.py') else '—'} | "
    f"`{job['ok_codes']}` |"
    for job in sorted(found, key=lambda j: j["name"])
  )
  out.append("")

  locks: dict[str, list[dict]] = {}
  for job in found:
    if job["lock"]:
      locks.setdefault(job["lock"], []).append(job)
  out.append("**Locks.** A held lock is recorded as a skip, not silence "
             "(`cron_job.py --lock`); three consecutive skips alert.")
  out.append("")
  out.append("| Lock | Holders | Waiters |")
  out.append("| --- | --- | --- |")
  for lock, holders in sorted(locks.items()):
    waiters = ", ".join(
      f"`{h['name']}` ({h['wait']}s)" for h in holders if h["wait"]
    ) or "— (all non-blocking)"
    out.append(f"| `{lock}` | {len(holders)} | {waiters} |")
  out.append("")

  defaulted = [j["name"] for j in found if j["ok_codes"].endswith("(default)")]
  out.append(
    f"**`--ok-codes`.** {len(found) - len(defaulted)} of {len(found)} jobs declare it "
    f"explicitly; {len(defaulted)} inherit the `0,1` default, which swallows exit 1."
  )
  out.append("")
  out.append(END)
  return "\n".join(out)


def replace_block(doc_text: str, block: str) -> str:
  """Swap the generated region, or raise if the markers are missing."""
  start = doc_text.index(BEGIN)
  end = doc_text.index(END) + len(END)
  return doc_text[:start] + block + doc_text[end:]


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
  parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
  parser.add_argument("--check", action="store_true", help="Exit 1 if the doc is stale.")
  parser.add_argument("--write", action="store_true", help="Rewrite the doc in place.")
  return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
  args = parse_args(argv)
  if not CRONTAB.exists():
    print(f"ERROR: {CRONTAB} is missing", file=sys.stderr)
    return 2

  block = render(jobs(CRONTAB.read_text()))

  if not (args.check or args.write):
    print(block)
    return 0

  doc_text = DOC.read_text()
  if BEGIN not in doc_text or END not in doc_text:
    print(f"ERROR: {DOC} has no generated block markers", file=sys.stderr)
    return 2
  updated = replace_block(doc_text, block)

  if args.write:
    DOC.write_text(updated)
    print(f"    wrote the generated cron-fleet tables into {DOC.name}")
    return 0

  if updated != doc_text:
    print(
      f"    !!! {DOC.name}'s cron-fleet tables are stale.\n"
      "        The hand-maintained versions pointed at the wrong script twice.\n"
      "        Regenerate: python scripts/gen_pipeline_tables.py --write",
      file=sys.stderr,
    )
    return 1
  print("    ok: cron-fleet tables match cron/crontab and the script docstrings")
  return 0


if __name__ == "__main__":
  sys.exit(main())
